{"time":"2025-07-28T13:04:05.6437125+07:00","level":"INFO","msg":"stream: starting","core version":"0.21.0"}
{"time":"2025-07-28T13:04:39.5075541+07:00","level":"INFO","msg":"stream: created new stream","id":"p4gtuaoz"}
{"time":"2025-07-28T13:04:39.5075541+07:00","level":"INFO","msg":"stream: started","id":"p4gtuaoz"}
{"time":"2025-07-28T13:04:39.5075541+07:00","level":"INFO","msg":"handler: started","stream_id":"p4gtuaoz"}
{"time":"2025-07-28T13:04:39.5075541+07:00","level":"INFO","msg":"writer: Do: started","stream_id":"p4gtuaoz"}
{"time":"2025-07-28T13:04:39.5075541+07:00","level":"INFO","msg":"sender: started","stream_id":"p4gtuaoz"}
{"time":"2025-07-28T14:41:18.3465464+07:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.1.60:54464->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-07-28T14:41:19.4391592+07:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/qdao-cntt-ank/YOLOv5/p4gtuaoz/file_stream\": read tcp 192.168.1.60:55065->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-07-28T14:41:41.5357629+07:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-07-28T14:41:42.8909517+07:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/qdao-cntt-ank/YOLOv5/p4gtuaoz/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-07-28T14:42:07.2970154+07:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-07-28T14:42:08.7517099+07:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/qdao-cntt-ank/YOLOv5/p4gtuaoz/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-07-28T14:42:15.3199301+07:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-07-28T14:42:18.3398976+07:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/qdao-cntt-ank/YOLOv5/p4gtuaoz/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-07-28T14:45:53.44425+07:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/qdao-cntt-ank/YOLOv5/p4gtuaoz/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-07-28T14:46:05.3706247+07:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.1.60:55745->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-07-28T14:46:16.5206375+07:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/qdao-cntt-ank/YOLOv5/p4gtuaoz/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-07-29T11:02:55.4471922+07:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
{"time":"2025-07-30T00:51:37.4629441+07:00","level":"INFO","msg":"stream: closing","id":"p4gtuaoz"}
{"time":"2025-07-30T00:51:38.9525687+07:00","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-07-30T00:51:39.4114274+07:00","level":"INFO","msg":"handler: closed","stream_id":"p4gtuaoz"}
{"time":"2025-07-30T00:51:39.4114274+07:00","level":"INFO","msg":"sender: closed","stream_id":"p4gtuaoz"}
{"time":"2025-07-30T00:51:39.4114274+07:00","level":"INFO","msg":"writer: Close: closed","stream_id":"p4gtuaoz"}
{"time":"2025-07-30T00:51:39.4120929+07:00","level":"INFO","msg":"stream: closed","id":"p4gtuaoz"}
